### ISSUE TITLE
How to catch a invalid token in ZiggeoSdk.Videos.get

### ISSUE THREAD

**Issue by maurodesouza** [Ziggeo/ZiggeoNodeSdk#25]
Hi!

I trying to make a validation by video token, in request is send the token and i would like the validate if the token is valid

So i trying to use the ZiggeoSdk.Videos.get, but it doesn't emit/return nothing when the token is invalid

How to catch a invalid token in ZiggeoSdk.Videos.get?

My node version 12.13.0

**Comment by Bane-D** [comment]
Hi Mauro,

If you do not mind, can you tell us how you are getting the token in the first place? It would help to know what kind of information you could potentially have and then need to confirm it is token, as well as what kind of validation you need.

Generally, as soon as the media token is generated it will have meta data created. All fields at that time would be with general values, so just by getting data about them should be enough to confirm that you do have a token.

If you request data for non existing token then you might want to inspect the headers - however as per above and your own findings it would not really be needed.

Again, this depends on the type of validation you are interested in.

**Comment by maurodesouza** [comment]
Hi @Bane-D 

As soon as the media token is generated, i need save it in my database, the problem is that endpoint to send the token is public, so anyone can send an invalid token, like { "token": "asdasd" }

So I need to validate that the video token is valid for saving to the database

The video is generated by react-ziggeo

**Comment by Bane-D** [comment]
OK I see.

Did you consider using webhooks? Basically the way that works is by our system reaching out to your system to let you know that video was created or that the same is ready (with all of the streams associated, etc.). You can see the list of the available ones here: https://ziggeo.com/docs/api/webhooks/list

What I would suggest is to consider saving the token from public page as is with any details you might need, and then waiting for the webhook to fire to let you know of the same token. At that point you can add more details or do any additional steps you might need.

That would be useful if you are also saving some other details like form data.

Another option is to listen to webhook to know when the video was created and at that point save the data into the database.

As webhooks are happening on the server side no one would know what data you are getting, nor would be able to change it. In that way you always know that it is a valid token (+ other media data). You would also not need to make additional calls or have additional codes for checks.
